//! Framework Control Definitions
//!
//! Contains the built-in control libraries for NIST CSF 2.0, SOC 2 Type II, and GDPR.

use crate::grc::models::{Control, Framework, NistFunction, Soc2Category, GdprChapter};
use uuid::Uuid;

/// Get all controls for a specific framework
pub fn get_framework_controls(framework: Framework) -> Vec<Control> {
    match framework {
        Framework::NistCsf2 => get_nist_csf2_controls(),
        Framework::Soc2TypeII => get_soc2_controls(),
        Framework::Gdpr => get_gdpr_controls(),
    }
}

/// Get all available frameworks with their metadata
pub fn get_available_frameworks() -> Vec<FrameworkInfo> {
    Framework::all()
        .into_iter()
        .map(|f| FrameworkInfo {
            id: format!("{:?}", f),
            name: f.display_name().to_string(),
            description: f.description().to_string(),
            control_count: get_framework_controls(f).len(),
            categories: get_framework_categories(f),
        })
        .collect()
}

/// Framework metadata
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FrameworkInfo {
    pub id: String,
    pub name: String,
    pub description: String,
    pub control_count: usize,
    pub categories: Vec<CategoryInfo>,
}

/// Category metadata
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CategoryInfo {
    pub code: String,
    pub name: String,
    pub description: String,
    pub color: String,
}

fn get_framework_categories(framework: Framework) -> Vec<CategoryInfo> {
    match framework {
        Framework::NistCsf2 => NistFunction::all()
            .into_iter()
            .map(|f| CategoryInfo {
                code: f.code().to_string(),
                name: f.display_name().to_string(),
                description: f.description().to_string(),
                color: f.color().to_string(),
            })
            .collect(),
        Framework::Soc2TypeII => Soc2Category::all()
            .into_iter()
            .map(|c| CategoryInfo {
                code: c.code().to_string(),
                name: c.display_name().to_string(),
                description: format!("{} trust services criteria", c.display_name()),
                color: c.color().to_string(),
            })
            .collect(),
        Framework::Gdpr => GdprChapter::all()
            .into_iter()
            .map(|c| CategoryInfo {
                code: c.code().to_string(),
                name: c.display_name().to_string(),
                description: format!("GDPR {}", c.display_name()),
                color: c.color().to_string(),
            })
            .collect(),
    }
}

/// NIST CSF 2.0 Controls
fn get_nist_csf2_controls() -> Vec<Control> {
    vec![
        // GOVERN Function
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "GV.OC-01".to_string(),
            category: "GV".to_string(),
            subcategory: Some("Organizational Context".to_string()),
            title: "Organizational Mission".to_string(),
            description: "The organizational mission is understood and informs cybersecurity risk management".to_string(),
            guidance: Some("Document how cybersecurity supports organizational objectives".to_string()),
            cross_references: vec!["CC1.1".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "GV.RM-01".to_string(),
            category: "GV".to_string(),
            subcategory: Some("Risk Management Strategy".to_string()),
            title: "Risk Management Objectives".to_string(),
            description: "Risk management objectives are established and agreed to by organizational stakeholders".to_string(),
            guidance: Some("Define risk appetite and tolerance levels".to_string()),
            cross_references: vec!["CC3.1".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "GV.RR-01".to_string(),
            category: "GV".to_string(),
            subcategory: Some("Roles & Responsibilities".to_string()),
            title: "Cybersecurity Roles".to_string(),
            description: "Organizational leadership defines and communicates cybersecurity roles and responsibilities".to_string(),
            guidance: Some("Establish RACI matrix for cybersecurity functions".to_string()),
            cross_references: vec!["CC1.3".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "GV.PO-01".to_string(),
            category: "GV".to_string(),
            subcategory: Some("Policy".to_string()),
            title: "Cybersecurity Policy".to_string(),
            description: "A policy for managing cybersecurity risks is established based on organizational context".to_string(),
            guidance: Some("Develop comprehensive information security policy".to_string()),
            cross_references: vec!["CC1.1".to_string(), "Art. 24".to_string()],
            priority: 5,
        },

        // IDENTIFY Function
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "ID.AM-01".to_string(),
            category: "ID".to_string(),
            subcategory: Some("Asset Management".to_string()),
            title: "Hardware Inventory".to_string(),
            description: "Inventories of hardware managed by the organization are maintained".to_string(),
            guidance: Some("Implement automated asset discovery and maintain CMDB".to_string()),
            cross_references: vec!["CC6.1".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "ID.AM-02".to_string(),
            category: "ID".to_string(),
            subcategory: Some("Asset Management".to_string()),
            title: "Software Inventory".to_string(),
            description: "Inventories of software, services, and systems managed by the organization are maintained".to_string(),
            guidance: Some("Deploy software asset management tools".to_string()),
            cross_references: vec!["CC6.1".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "ID.AM-03".to_string(),
            category: "ID".to_string(),
            subcategory: Some("Asset Management".to_string()),
            title: "Data Flow Mapping".to_string(),
            description: "Representations of the organization's authorized network communication and data flows are maintained".to_string(),
            guidance: Some("Create and maintain network diagrams and data flow maps".to_string()),
            cross_references: vec!["CC6.1".to_string(), "Art. 30".to_string()],
            priority: 3,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "ID.RA-01".to_string(),
            category: "ID".to_string(),
            subcategory: Some("Risk Assessment".to_string()),
            title: "Vulnerability Identification".to_string(),
            description: "Vulnerabilities in assets are identified, validated, and recorded".to_string(),
            guidance: Some("Implement vulnerability scanning and penetration testing".to_string()),
            cross_references: vec!["CC4.1".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "ID.RA-02".to_string(),
            category: "ID".to_string(),
            subcategory: Some("Risk Assessment".to_string()),
            title: "Threat Intelligence".to_string(),
            description: "Cyber threat intelligence is received from information sharing forums and sources".to_string(),
            guidance: Some("Subscribe to threat intelligence feeds and participate in ISACs".to_string()),
            cross_references: vec!["CC3.2".to_string()],
            priority: 3,
        },

        // PROTECT Function
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.AA-01".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Identity Management & Access Control".to_string()),
            title: "Identity Management".to_string(),
            description: "Identities and credentials for authorized users, services, and hardware are managed".to_string(),
            guidance: Some("Implement identity governance with lifecycle management".to_string()),
            cross_references: vec!["CC6.1".to_string(), "CC6.2".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.AA-02".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Identity Management & Access Control".to_string()),
            title: "Authentication".to_string(),
            description: "Identities are proofed and bound to credentials based on the context of interactions".to_string(),
            guidance: Some("Implement MFA for all privileged and remote access".to_string()),
            cross_references: vec!["CC6.1".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.AA-03".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Identity Management & Access Control".to_string()),
            title: "Access Control".to_string(),
            description: "Access permissions, entitlements, and authorizations are managed".to_string(),
            guidance: Some("Implement role-based access control with least privilege".to_string()),
            cross_references: vec!["CC6.2".to_string(), "CC6.3".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.DS-01".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Data Security".to_string()),
            title: "Data-at-Rest Protection".to_string(),
            description: "The confidentiality, integrity, and availability of data-at-rest are protected".to_string(),
            guidance: Some("Implement encryption for data at rest".to_string()),
            cross_references: vec!["CC6.1".to_string(), "Art. 32".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.DS-02".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Data Security".to_string()),
            title: "Data-in-Transit Protection".to_string(),
            description: "The confidentiality, integrity, and availability of data-in-transit are protected".to_string(),
            guidance: Some("Implement TLS 1.3 for all network communications".to_string()),
            cross_references: vec!["CC6.1".to_string(), "Art. 32".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.PS-01".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Platform Security".to_string()),
            title: "Configuration Management".to_string(),
            description: "Configuration management practices are established and applied".to_string(),
            guidance: Some("Implement configuration baselines and drift detection".to_string()),
            cross_references: vec!["CC6.1".to_string(), "CC7.1".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "PR.IR-01".to_string(),
            category: "PR".to_string(),
            subcategory: Some("Technology Infrastructure Resilience".to_string()),
            title: "Backup & Recovery".to_string(),
            description: "Backups of data are conducted, maintained, and tested".to_string(),
            guidance: Some("Implement 3-2-1 backup strategy with regular testing".to_string()),
            cross_references: vec!["A1.2".to_string()],
            priority: 5,
        },

        // DETECT Function
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "DE.CM-01".to_string(),
            category: "DE".to_string(),
            subcategory: Some("Continuous Monitoring".to_string()),
            title: "Network Monitoring".to_string(),
            description: "Networks and network services are monitored to find potentially adverse events".to_string(),
            guidance: Some("Deploy network detection and response (NDR) solutions".to_string()),
            cross_references: vec!["CC7.2".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "DE.CM-02".to_string(),
            category: "DE".to_string(),
            subcategory: Some("Continuous Monitoring".to_string()),
            title: "Physical Environment Monitoring".to_string(),
            description: "The physical environment is monitored to find potentially adverse events".to_string(),
            guidance: Some("Implement physical access monitoring and environmental controls".to_string()),
            cross_references: vec!["CC6.4".to_string()],
            priority: 3,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "DE.CM-03".to_string(),
            category: "DE".to_string(),
            subcategory: Some("Continuous Monitoring".to_string()),
            title: "Personnel Activity Monitoring".to_string(),
            description: "Personnel activity and technology usage are monitored to find potentially adverse events".to_string(),
            guidance: Some("Implement user behavior analytics (UBA)".to_string()),
            cross_references: vec!["CC6.2".to_string()],
            priority: 3,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "DE.AE-02".to_string(),
            category: "DE".to_string(),
            subcategory: Some("Adverse Event Analysis".to_string()),
            title: "Event Correlation".to_string(),
            description: "Potentially adverse events are analyzed to better understand associated activities".to_string(),
            guidance: Some("Deploy SIEM with correlation rules".to_string()),
            cross_references: vec!["CC7.2".to_string()],
            priority: 4,
        },

        // RESPOND Function
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "RS.MA-01".to_string(),
            category: "RS".to_string(),
            subcategory: Some("Incident Management".to_string()),
            title: "Incident Response Plan".to_string(),
            description: "The incident response plan is executed in coordination with relevant third parties".to_string(),
            guidance: Some("Develop and test incident response procedures".to_string()),
            cross_references: vec!["CC7.4".to_string(), "Art. 33".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "RS.MA-02".to_string(),
            category: "RS".to_string(),
            subcategory: Some("Incident Management".to_string()),
            title: "Incident Triage".to_string(),
            description: "Incidents are categorized, prioritized, and escalated".to_string(),
            guidance: Some("Establish incident classification and escalation procedures".to_string()),
            cross_references: vec!["CC7.3".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "RS.CO-02".to_string(),
            category: "RS".to_string(),
            subcategory: Some("Incident Response Reporting & Communication".to_string()),
            title: "Incident Reporting".to_string(),
            description: "Internal and external stakeholders are notified of incidents".to_string(),
            guidance: Some("Establish notification procedures for various incident types".to_string()),
            cross_references: vec!["CC7.4".to_string(), "Art. 33".to_string(), "Art. 34".to_string()],
            priority: 4,
        },

        // RECOVER Function
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "RC.RP-01".to_string(),
            category: "RC".to_string(),
            subcategory: Some("Incident Recovery Plan Execution".to_string()),
            title: "Recovery Plan Execution".to_string(),
            description: "The recovery portion of the incident response plan is executed".to_string(),
            guidance: Some("Develop and test business continuity and disaster recovery plans".to_string()),
            cross_references: vec!["A1.3".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "RC.RP-02".to_string(),
            category: "RC".to_string(),
            subcategory: Some("Incident Recovery Plan Execution".to_string()),
            title: "Recovery Validation".to_string(),
            description: "Recovery actions are verified".to_string(),
            guidance: Some("Conduct post-recovery validation and testing".to_string()),
            cross_references: vec!["A1.3".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::NistCsf2,
            code: "RC.CO-03".to_string(),
            category: "RC".to_string(),
            subcategory: Some("Incident Recovery Communication".to_string()),
            title: "Recovery Communication".to_string(),
            description: "Recovery activities and progress are communicated to stakeholders".to_string(),
            guidance: Some("Establish recovery status reporting procedures".to_string()),
            cross_references: vec!["CC7.5".to_string()],
            priority: 3,
        },
    ]
}

/// SOC 2 Type II Controls (Common Criteria)
fn get_soc2_controls() -> Vec<Control> {
    vec![
        // Security (Common Criteria)
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC1.1".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Control Environment".to_string()),
            title: "COSO Principle 1".to_string(),
            description: "The entity demonstrates a commitment to integrity and ethical values".to_string(),
            guidance: Some("Establish and communicate code of conduct".to_string()),
            cross_references: vec!["GV.OC-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC1.2".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Control Environment".to_string()),
            title: "COSO Principle 2".to_string(),
            description: "The board of directors demonstrates independence from management and exercises oversight".to_string(),
            guidance: Some("Document board oversight of IT and security".to_string()),
            cross_references: vec!["GV.RR-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC1.3".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Control Environment".to_string()),
            title: "COSO Principle 3".to_string(),
            description: "Management establishes structures, reporting lines, and authorities".to_string(),
            guidance: Some("Define organizational structure and reporting relationships".to_string()),
            cross_references: vec!["GV.RR-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC3.1".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Risk Assessment".to_string()),
            title: "COSO Principle 6".to_string(),
            description: "The entity specifies objectives with sufficient clarity to enable identification of risks".to_string(),
            guidance: Some("Document IT and security objectives".to_string()),
            cross_references: vec!["GV.RM-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC3.2".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Risk Assessment".to_string()),
            title: "COSO Principle 7".to_string(),
            description: "The entity identifies risks to the achievement of its objectives".to_string(),
            guidance: Some("Conduct regular risk assessments".to_string()),
            cross_references: vec!["ID.RA-02".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC4.1".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Monitoring Activities".to_string()),
            title: "COSO Principle 16".to_string(),
            description: "The entity selects and develops ongoing and/or separate evaluations".to_string(),
            guidance: Some("Implement continuous monitoring and periodic assessments".to_string()),
            cross_references: vec!["ID.RA-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC6.1".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Logical and Physical Access Controls".to_string()),
            title: "Logical Access Security".to_string(),
            description: "The entity implements logical access security software, infrastructure, and architectures".to_string(),
            guidance: Some("Deploy identity and access management controls".to_string()),
            cross_references: vec!["PR.AA-01".to_string(), "PR.AA-02".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC6.2".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Logical and Physical Access Controls".to_string()),
            title: "User Registration & Authorization".to_string(),
            description: "Prior to issuing system credentials, the entity registers authorized users".to_string(),
            guidance: Some("Implement formal user provisioning process".to_string()),
            cross_references: vec!["PR.AA-01".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC6.3".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Logical and Physical Access Controls".to_string()),
            title: "Access Removal".to_string(),
            description: "The entity removes access to protected information when access is no longer required".to_string(),
            guidance: Some("Implement user deprovisioning process".to_string()),
            cross_references: vec!["PR.AA-03".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC6.4".to_string(),
            category: "CC".to_string(),
            subcategory: Some("Logical and Physical Access Controls".to_string()),
            title: "Physical Access".to_string(),
            description: "The entity restricts physical access to facilities and protected information".to_string(),
            guidance: Some("Implement physical security controls".to_string()),
            cross_references: vec!["DE.CM-02".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC7.1".to_string(),
            category: "CC".to_string(),
            subcategory: Some("System Operations".to_string()),
            title: "Detection and Monitoring".to_string(),
            description: "The entity uses detection and monitoring procedures to identify changes".to_string(),
            guidance: Some("Implement change detection mechanisms".to_string()),
            cross_references: vec!["PR.PS-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC7.2".to_string(),
            category: "CC".to_string(),
            subcategory: Some("System Operations".to_string()),
            title: "Security Event Monitoring".to_string(),
            description: "The entity monitors system components for anomalies and security events".to_string(),
            guidance: Some("Deploy security monitoring and SIEM".to_string()),
            cross_references: vec!["DE.CM-01".to_string(), "DE.AE-02".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC7.3".to_string(),
            category: "CC".to_string(),
            subcategory: Some("System Operations".to_string()),
            title: "Security Incident Evaluation".to_string(),
            description: "The entity evaluates security events to determine whether they constitute security incidents".to_string(),
            guidance: Some("Establish incident triage procedures".to_string()),
            cross_references: vec!["RS.MA-02".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC7.4".to_string(),
            category: "CC".to_string(),
            subcategory: Some("System Operations".to_string()),
            title: "Incident Response".to_string(),
            description: "The entity responds to identified security incidents by executing a defined incident response program".to_string(),
            guidance: Some("Develop and test incident response plan".to_string()),
            cross_references: vec!["RS.MA-01".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "CC7.5".to_string(),
            category: "CC".to_string(),
            subcategory: Some("System Operations".to_string()),
            title: "Recovery from Incidents".to_string(),
            description: "The entity identifies, develops, and implements activities to recover from incidents".to_string(),
            guidance: Some("Implement recovery procedures".to_string()),
            cross_references: vec!["RC.CO-03".to_string()],
            priority: 4,
        },

        // Availability
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "A1.1".to_string(),
            category: "A".to_string(),
            subcategory: Some("Availability".to_string()),
            title: "Capacity Management".to_string(),
            description: "The entity maintains, monitors, and evaluates current processing capacity".to_string(),
            guidance: Some("Implement capacity planning and monitoring".to_string()),
            cross_references: vec![],
            priority: 3,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "A1.2".to_string(),
            category: "A".to_string(),
            subcategory: Some("Availability".to_string()),
            title: "Backup and Recovery".to_string(),
            description: "The entity authorizes, designs, develops, and implements backup procedures".to_string(),
            guidance: Some("Implement backup and recovery procedures".to_string()),
            cross_references: vec!["PR.IR-01".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "A1.3".to_string(),
            category: "A".to_string(),
            subcategory: Some("Availability".to_string()),
            title: "Recovery Testing".to_string(),
            description: "The entity tests backup and recovery procedures".to_string(),
            guidance: Some("Conduct regular DR tests".to_string()),
            cross_references: vec!["RC.RP-01".to_string(), "RC.RP-02".to_string()],
            priority: 4,
        },

        // Confidentiality
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "C1.1".to_string(),
            category: "C".to_string(),
            subcategory: Some("Confidentiality".to_string()),
            title: "Confidential Information Identification".to_string(),
            description: "The entity identifies and maintains confidential information".to_string(),
            guidance: Some("Implement data classification".to_string()),
            cross_references: vec!["PR.DS-01".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Soc2TypeII,
            code: "C1.2".to_string(),
            category: "C".to_string(),
            subcategory: Some("Confidentiality".to_string()),
            title: "Confidential Information Disposal".to_string(),
            description: "The entity disposes of confidential information".to_string(),
            guidance: Some("Implement secure data disposal procedures".to_string()),
            cross_references: vec![],
            priority: 3,
        },
    ]
}

/// GDPR Controls
fn get_gdpr_controls() -> Vec<Control> {
    vec![
        // Principles (Chapter 2)
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 5(1)(a)".to_string(),
            category: "CH2".to_string(),
            subcategory: Some("Principles".to_string()),
            title: "Lawfulness, Fairness, Transparency".to_string(),
            description: "Personal data shall be processed lawfully, fairly and in a transparent manner".to_string(),
            guidance: Some("Document lawful basis for processing, provide clear privacy notices".to_string()),
            cross_references: vec![],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 5(1)(b)".to_string(),
            category: "CH2".to_string(),
            subcategory: Some("Principles".to_string()),
            title: "Purpose Limitation".to_string(),
            description: "Personal data shall be collected for specified, explicit and legitimate purposes".to_string(),
            guidance: Some("Document purposes of processing in ROPA".to_string()),
            cross_references: vec![],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 5(1)(c)".to_string(),
            category: "CH2".to_string(),
            subcategory: Some("Principles".to_string()),
            title: "Data Minimization".to_string(),
            description: "Personal data shall be adequate, relevant and limited to what is necessary".to_string(),
            guidance: Some("Review data collection practices, implement data minimization".to_string()),
            cross_references: vec![],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 5(1)(f)".to_string(),
            category: "CH2".to_string(),
            subcategory: Some("Principles".to_string()),
            title: "Integrity and Confidentiality".to_string(),
            description: "Personal data shall be processed with appropriate security measures".to_string(),
            guidance: Some("Implement technical and organizational security measures".to_string()),
            cross_references: vec!["PR.DS-01".to_string(), "PR.DS-02".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 6".to_string(),
            category: "CH2".to_string(),
            subcategory: Some("Lawful Basis".to_string()),
            title: "Lawfulness of Processing".to_string(),
            description: "Processing shall be lawful only if one of the conditions in Article 6(1) applies".to_string(),
            guidance: Some("Document lawful basis for each processing activity".to_string()),
            cross_references: vec![],
            priority: 5,
        },

        // Data Subject Rights (Chapter 3)
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 12".to_string(),
            category: "CH3".to_string(),
            subcategory: Some("Transparency".to_string()),
            title: "Transparent Communication".to_string(),
            description: "Controller shall take appropriate measures to provide information in a concise, transparent form".to_string(),
            guidance: Some("Implement clear privacy notices and communication procedures".to_string()),
            cross_references: vec![],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 15".to_string(),
            category: "CH3".to_string(),
            subcategory: Some("Access Rights".to_string()),
            title: "Right of Access".to_string(),
            description: "Data subject shall have the right to obtain confirmation and access to personal data".to_string(),
            guidance: Some("Implement subject access request (SAR) process".to_string()),
            cross_references: vec![],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 17".to_string(),
            category: "CH3".to_string(),
            subcategory: Some("Erasure Rights".to_string()),
            title: "Right to Erasure".to_string(),
            description: "Data subject shall have the right to obtain erasure of personal data".to_string(),
            guidance: Some("Implement data deletion process and right to be forgotten".to_string()),
            cross_references: vec![],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 20".to_string(),
            category: "CH3".to_string(),
            subcategory: Some("Portability Rights".to_string()),
            title: "Right to Data Portability".to_string(),
            description: "Data subject shall have the right to receive personal data in a portable format".to_string(),
            guidance: Some("Implement data export functionality".to_string()),
            cross_references: vec![],
            priority: 3,
        },

        // Controller & Processor (Chapter 4)
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 24".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Controller Obligations".to_string()),
            title: "Responsibility of Controller".to_string(),
            description: "Controller shall implement appropriate technical and organizational measures".to_string(),
            guidance: Some("Establish data protection governance framework".to_string()),
            cross_references: vec!["GV.PO-01".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 25".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Privacy by Design".to_string()),
            title: "Data Protection by Design and Default".to_string(),
            description: "Controller shall implement appropriate technical measures designed to implement data protection principles".to_string(),
            guidance: Some("Integrate privacy into system design and development".to_string()),
            cross_references: vec![],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 28".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Processor Requirements".to_string()),
            title: "Processor Contracts".to_string(),
            description: "Processing by a processor shall be governed by a contract".to_string(),
            guidance: Some("Implement Data Processing Agreements with all processors".to_string()),
            cross_references: vec![],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 30".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Records".to_string()),
            title: "Records of Processing Activities".to_string(),
            description: "Controller shall maintain a record of processing activities".to_string(),
            guidance: Some("Create and maintain Records of Processing Activities (ROPA)".to_string()),
            cross_references: vec!["ID.AM-03".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 32".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Security".to_string()),
            title: "Security of Processing".to_string(),
            description: "Controller and processor shall implement appropriate security measures".to_string(),
            guidance: Some("Implement encryption, pseudonymization, and security controls".to_string()),
            cross_references: vec!["PR.DS-01".to_string(), "PR.DS-02".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 33".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Breach Notification".to_string()),
            title: "Notification to Supervisory Authority".to_string(),
            description: "Controller shall notify the supervisory authority of a personal data breach within 72 hours".to_string(),
            guidance: Some("Implement breach detection and 72-hour notification process".to_string()),
            cross_references: vec!["RS.MA-01".to_string(), "RS.CO-02".to_string()],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 34".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Breach Notification".to_string()),
            title: "Communication to Data Subject".to_string(),
            description: "Controller shall communicate breach to data subject when high risk exists".to_string(),
            guidance: Some("Implement data subject breach notification process".to_string()),
            cross_references: vec!["RS.CO-02".to_string()],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 35".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("Impact Assessment".to_string()),
            title: "Data Protection Impact Assessment".to_string(),
            description: "Controller shall carry out a DPIA for high-risk processing".to_string(),
            guidance: Some("Conduct DPIAs for new high-risk processing activities".to_string()),
            cross_references: vec![],
            priority: 4,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 37".to_string(),
            category: "CH4".to_string(),
            subcategory: Some("DPO".to_string()),
            title: "Data Protection Officer".to_string(),
            description: "Controller shall designate a DPO in certain circumstances".to_string(),
            guidance: Some("Appoint DPO if required, document rationale if not".to_string()),
            cross_references: vec![],
            priority: 4,
        },

        // Transfers (Chapter 5)
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 44".to_string(),
            category: "CH5".to_string(),
            subcategory: Some("Transfer Principles".to_string()),
            title: "General Principle for Transfers".to_string(),
            description: "Transfers to third countries shall only take place under specified conditions".to_string(),
            guidance: Some("Document transfer mechanisms for international data transfers".to_string()),
            cross_references: vec![],
            priority: 5,
        },
        Control {
            id: Uuid::new_v4().to_string(),
            framework: Framework::Gdpr,
            code: "Art. 46".to_string(),
            category: "CH5".to_string(),
            subcategory: Some("Transfer Safeguards".to_string()),
            title: "Appropriate Safeguards".to_string(),
            description: "Controller may transfer personal data with appropriate safeguards".to_string(),
            guidance: Some("Implement SCCs or other approved transfer mechanisms".to_string()),
            cross_references: vec![],
            priority: 4,
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_framework_controls_not_empty() {
        for framework in Framework::all() {
            let controls = get_framework_controls(framework);
            assert!(!controls.is_empty(), "{} should have controls", framework);
        }
    }

    #[test]
    fn test_available_frameworks() {
        let frameworks = get_available_frameworks();
        assert_eq!(frameworks.len(), 3);
    }
}
